### ISSUE TITLE
Wrong repository name in the sample

### ISSUE THREAD

**Issue by ydaponte** [abeebu/purview-custom-permissions#3]
On the sample code included in the readme file you point to:
uses: abeebu/purview-assign-permissions@v1

I think you are trying to refer to the repo as in abeebu/purview-custom-permissions? Or am I missing something?
Either way the name of the repo will change when we move to Azure Samples - just want to make sure it is consistent.

**Comment by abeebu** [comment]
Yes I am. I left that as a placeholder because I knew the repo was still going to change anyway. Yes, it's supposed to be consistent with the repo name @ydaponte

**Comment by ydaponte** [comment]
Still I couldn't make it work referencing a new repo I've created on my github to do the testing. The only way I could reference it and worked was with ./ - do you have thoughts for this? cc: @abeebu

**Comment by abeebu** [comment]
@ydaponte I suppose I'd have to publish it  in the marketplace first before you can use in a new repo. Should I go ahead and publish so you can test?

**Comment by abeebu** [comment]
I have published for the purpose of testing. I can delist it later when we are ready

**Comment by ydaponte** [comment]
Ah, ok - maybe this is also something we need to highlight in the documentation. I will try to test it again.
